### ISSUE TITLE
Using davinci-003 makes results worse?

### ISSUE THREAD

**Issue by kpister** [stanfordnlp/dsp#19]
Have others noticed this issue as well? I swapped the LM to be `davinci-text-003` and my results are actually worse than with `davinci-text-002`.

Some of the answers are pretty "obviously wrong" too:

```
Question: What year was the party of the winner of the 1971 San Francisco mayoral election founded?

Rationale: Let's think step by step. First, we need to identify the winner of the 1971 San Francisco mayoral election. From the context, we can see that the winner of the 1971 San Francisco mayoral election was Joseph Alioto. Next, we need to identify the date in which the party of Joseph Alioto was founded. 

From the context, we can see that the Democratic Party of Serbia (of which Joseph Alioto was a member) was founded on February 3, 1990.
```

On `multihop_QA_v2`, instead of 84.6% results, I am getting 53.8%. `multihop_QA_v1` achieved ~34%.

**Comment by okhat** [comment]
Thanks for testing this!I haven’t worked with 003 in any serious capacity before, but there are academic results that show it is in fact worse for academic tasks than 002. It could still be better for casual use, open-ended generation, or chatbots, etc. Happy to find references if needed. 

That said, I absolutely wouldn’t read much at all into the score on the 13 examples. A difference of 4 matches is too small to be representative in a statistical sense. The examples are only given for illustration, as the notebook says, rather than a benchmark.

But it might still be interesting to study the ways in which the new model makes mistakes not made by the older model.
